[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "playing_cards_created = {true}"
position = "at"
payload = '''
playing_cards_created = {_card}
'''
match_indent = true
times = 1